manifest:
  version: 1.0

  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: v4.4.0
      import:
        name-allowlist:
          - hal_espressif
          - cmsis_6
          - hal_nxp
          - hal_stm32
          - hal_nordic
          - hal_xtensa
        path-prefix: deps
